### ISSUE TITLE
IP Address Discrepancy in config.h and via DHCP 

### ISSUE THREAD

**Issue by MrBearing** [mROS-base/mros2#41]
config.hで設定するIPアドレスとDHCPから取得したIPアドレスが異なると、プログラムが正しく動作しません。
IPアドレスをDHCPから取得した場合においても、config.hの設定変更なく動作することが望ましいです。

問題の解決が難しいようであれば、Cofig.hとDHCPで取得したIPアドレスに差がある場合にワーニングないしエラーメッセージを追加いただけるとありがたいです。

**Comment by takasehideki** [comment]
@MrBearing https://github.com/mROS-base/mros2/pull/45 で対応してみました．

これの Release v0.5.1 (and v0.5.3) を取り込んだ実装を mros2-esp32 でも公開しています．お試しあれ〜
https://github.com/mROS-base/mros2-esp32/pull/13

**Comment by takasehideki** [comment]
mros2-mbed はそもそもDHCPがうまくいかない？？ようなので contribution お待ちしていますとかそういうことおもってないです:D
https://github.com/mROS-base/mros2-mbed/issues/43

**Comment by takasehideki** [comment]
@MrBearing :+1: と :tada: で反応いただいているので，これは大丈夫だったでしょうか．ひとまず close としますがなにか問題あれば遠慮なく reopen いただいて構いません．

**Comment by MrBearing** [comment]
問題なかったです。

Close遅くなり申し訳ありません。
